### PR TITLE
Fix omitted case in `leftmost_arg`

### LINKED ISSUE #805: Inconsistency between composition operations
There seems to be a bug resulting in an inconsistency between composition written in classical and diagrammatic order.

See the reproduction example below:

```
# Tested with Catlab v0.15.0
using Catlab.Graphs, Catlab.Graphics
using Catlab.Theories, Catlab.CategoricalAlgebra, Catlab.Programs

g = path_graph(Graph, 3)

# Works fine!
h₁ = @migrate Graph g begin
  V => @cases (v₁::V; v₂::V)
  E => E
  src => v₁ ∘ src
  tgt => v₂ ∘ tgt
end

# MethodError: Cannot `convert` an object of type Nothing to an object of type Symbol
h₂ = @migrate Graph g begin
  V => @cases (v₁::V; v₂::V)
  E => E
  src => src ⋅ v₁
  tgt => tgt ⋅ v₂
end

# Works fine!
k₁ = @migrate Graph g begin
  V => V
  E => @join begin
    (e₁, e₂)::E
  end
  src => e₁ ⋅ src
  tgt => e₂ ⋅ tgt
end

# MethodError: Cannot `convert` an object of type Nothing to an object of type Symbol
k₂ = @migrate Graph g begin
  V => V
  E => @join begin
    (e₁, e₂)::E
  end
  src => src ∘ e₁
  tgt => tgt ∘ e₂
end
```

### PR DESCRIPTION
**Pull request by KevinArlin**
Resolves #805 .

The `leftmost_arg` function that's used to build `AST.Apply` and `AST.Coapply`s was missing a case for what to do when giving a composition operator that works in the opposite order of the target AST type.

### CODE REVIEW

File: src/programs/DiagrammaticPrograms.jl [hunk 1]
```diff
@@ -1105,7 +1105,7 @@ end
 function parse_mapping_ast(body, dom; kw...)
   parse_mapping_ast((rhs, _) -> parse_ob_ast(rhs), body, dom; kw...)
 end
-
+#ugh wtf is leftmost arg's even deal with \circ
```
Comment (epatters) [inline src/programs/DiagrammaticPrograms.jl:1108]: This comment should be removed.

**Review by epatters — CHANGES_REQUESTED** [review]
Thanks Kevin!

File: src/programs/DiagrammaticPrograms.jl (hunk 1 above)
Comment (KevinArlin) [reply src/programs/DiagrammaticPrograms.jl:1108]: Whoops :)

Comment (KevinArlin) [reply src/programs/DiagrammaticPrograms.jl]: OK, it's removed.

**Review by epatters — APPROVED** [review]
